"""init schema

Revision ID: 9db12c372ecd
Revises: 
Create Date: 2026-02-02 10:50:33.852537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9db12c372ecd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('plugin_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('params_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_runs_dataset_id', 'runs', ['dataset_id'], unique=False)
    op.create_index('idx_runs_status', 'runs', ['status'], unique=False)
    op.create_table('results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('result_type', sa.String(), nullable=False),
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('metrics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('footprint_wkt', sa.Text(), nullable=True),
    sa.Column('footprint_geom', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_results_footprint_geom', 'results', ['footprint_geom'], unique=False, postgresql_using='gist')
    op.create_index('idx_results_geom', 'results', ['footprint_geom'], unique=False, postgresql_using='gist')
    op.create_index('idx_results_run_id', 'results', ['run_id'], unique=False)
    op.create_index('idx_results_type', 'results', ['result_type'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('result_id', sa.String(), nullable=False),
    sa.Column('corrected_label', sa.String(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_feedback_result_id', 'feedback', ['result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_feedback_result_id', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('idx_results_type', table_name='results')
    op.drop_index('idx_results_run_id', table_name='results')
    op.drop_index('idx_results_geom', table_name='results', postgresql_using='gist')
    op.drop_index('idx_results_footprint_geom', table_name='results', postgresql_using='gist')
    op.drop_table('results')
    op.drop_index('idx_runs_status', table_name='runs')
    op.drop_index('idx_runs_dataset_id', table_name='runs')
    op.drop_table('runs')
    op.drop_table('datasets')
    # ### end Alembic commands ###
